# https://taskfile.dev

version: '3'

tasks:
  default:
    - task: build

  clear:
    rm -rf bin/*

  perm:
    chmod -R +x bin

  build:
    desc: Локальный билд бинарников
    deps:
      - clear
      - perm
    cmds:
      - go build -gcflags "all=-N -l" -o ./bin/multichecker ./cmd/multichecker/*.go